"use client";

import { useEffect, useMemo, useState } from "react";
import { API_BASE_URL } from "@/lib/api";

interface Transaction { date: string; description: string; main_description?: string; details?: string[]; amount: number; debit?: number | null; credit?: number | null; ai_suggested_account?: string; }
interface LookupOption { id?: number | string; code?: string; name: string; label: string; }

function fmt(value?: number | null) { return Number(value || 0).toLocaleString("en-SA", { minimumFractionDigits: 2, maximumFractionDigits: 2 }); }
function clean(value?: string) { return (value || "").toLowerCase().replace(/[أإآ]/g, "ا").replace(/ى/g, "ي").replace(/ة/g, "ه").replace(/[\-_/.,:;()\[\]{}]/g, " ").replace(/\s+/g, " ").trim(); }
function textOf(txn: Transaction) { return clean(`${txn.description} ${txn.main_description || ""} ${(txn.details || []).join(" ")} ${txn.ai_suggested_account || ""}`); }
function termsFor(text: string) { if (/رسوم|عموله|charge|fee|commission/.test(text)) return ["مصروفات بنكية", "رسوم", "bank", "fee"]; if (/راتب|رواتب|salary|payroll|wps/.test(text)) return ["رواتب", "اجور", "salary", "payroll"]; if (/مورد|vendor|supplier|فاتوره|bill|purchase|سداد|sadad/.test(text)) return ["مورد", "موردون", "payable", "supplier", "vendor"]; if (/عميل|customer|client|تحصيل|ايراد|receipt|deposit|ايداع/.test(text)) return ["عميل", "عملاء", "receivable", "revenue", "customer"]; if (/ضريبه|vat|tax|زكاه|زكاة/.test(text)) return ["ضريبة", "vat", "tax", "زكاة"]; if (/ايجار|rent|lease/.test(text)) return ["ايجار", "rent", "lease"]; return ["تسوية", "وسيط", "suspense", "clearing"]; }
function score(label: string, text: string, terms: string[]) { const l = clean(label); let s = 0; terms.forEach(t => { if (l.includes(clean(t))) s += 10; }); l.split(" ").filter(t => t.length > 2).forEach(t => { if (text.includes(t)) s += 2; }); text.split(" ").filter(t => t.length > 3).forEach(t => { if (l.includes(t)) s += 1; }); return s; }
function best(options: LookupOption[], text: string, terms: string[]) { let found = { label: "", score: 0 }; options.forEach(o => { const label = o.label || `${o.code || ""} ${o.name || ""}`.trim(); const sc = score(label, text, terms); if (sc > found.score) found = { label, score: sc }; }); return found; }
function fallbackAccount(txn: Transaction) { const t = textOf(txn); if (txn.ai_suggested_account) return txn.ai_suggested_account; if (/رسوم|عموله|charge|fee|commission/.test(t)) return "مصروفات بنكية"; if (/راتب|رواتب|salary|payroll|wps/.test(t)) return "مصروفات الرواتب والأجور"; if (/مورد|vendor|supplier|فاتوره|bill|purchase|سداد|sadad/.test(t)) return "الموردون / مصروفات تحت التسوية"; if (/عميل|customer|client|تحصيل|ايراد|receipt|deposit|ايداع/.test(t)) return "العملاء / إيرادات تحت التسوية"; if (/ضريبه|vat|tax|زكاه|زكاة/.test(t)) return "ضرائب ورسوم حكومية"; if (/ايجار|rent|lease/.test(t)) return "مصروفات الإيجار"; return "حساب وسيط للمطابقة - يحتاج اعتماد"; }
function isDeposit(txn: Transaction) { return Number(txn.amount || 0) > 0 || (Number(txn.credit || 0) > 0 && Number(txn.debit || 0) === 0); }

function EntryRow({ txn, index, isAr, bankAccount, accounts, partners }: { txn: Transaction; index: number; isAr: boolean; bankAccount: string; accounts: LookupOption[]; partners: LookupOption[] }) {
  const t = textOf(txn);
  const accountGuess = useMemo(() => { const b = best(accounts, t, termsFor(t)); return b.score >= 8 ? b.label : fallbackAccount(txn); }, [accounts, t, txn]);
  const partnerGuess = useMemo(() => { const b = best(partners, t, []); return b.score >= 4 ? b.label : "غير محدد - اختر الشريك"; }, [partners, t]);
  const [account, setAccount] = useState(accountGuess);
  const [partner, setPartner] = useState(partnerGuess);
  useEffect(() => setAccount(accountGuess), [accountGuess]);
  useEffect(() => setPartner(partnerGuess), [partnerGuess]);
  const amount = Math.abs(Number(txn.amount || txn.credit || txn.debit || 0));
  const deposit = isDeposit(txn);
  const lines = deposit ? [{ account: bankAccount, partner, debit: amount, credit: 0 }, { account, partner, debit: 0, credit: amount }] : [{ account, partner, debit: amount, credit: 0 }, { account: bankAccount, partner, debit: 0, credit: amount }];
  return <div className="rounded-xl border border-cyan-500/25 bg-cyan-500/5 p-3 space-y-3"><div className="flex justify-between gap-3 flex-wrap"><div><p className="font-bold text-cyan-300">🧾 {isAr ? "قيد مقترح" : "Suggested entry"} #{index + 1}</p><p className="text-[10px] text-white/60">{txn.date} — {txn.main_description || txn.description}</p></div><p className="font-mono text-amber-300 font-bold">{fmt(amount)} SAR</p></div><div className="grid md:grid-cols-2 gap-2"><div><label className="block text-[10px] text-white/50 mb-1">{isAr ? "الحساب المقابل" : "Counter account"}</label><input list={`acc-${index}`} value={account} onChange={e => setAccount(e.target.value)} className="w-full bg-black/40 border border-cyan-500/30 rounded-lg px-2 py-2 text-xs text-white outline-none" /><datalist id={`acc-${index}`}>{accounts.map((a, i) => <option key={i} value={a.label} />)}</datalist></div><div><label className="block text-[10px] text-white/50 mb-1">{isAr ? "الشريك" : "Partner"}</label><input list={`par-${index}`} value={partner} onChange={e => setPartner(e.target.value)} className="w-full bg-black/40 border border-purple-500/30 rounded-lg px-2 py-2 text-xs text-white outline-none" /><datalist id={`par-${index}`}>{partners.map((p, i) => <option key={i} value={p.label} />)}</datalist></div></div><table className="w-full text-[10px] rounded-lg overflow-hidden border border-white/10"><thead className="bg-white/5 text-white/60"><tr><th className="p-2 text-right">{isAr ? "الحساب" : "Account"}</th><th className="p-2 text-right">{isAr ? "الشريك" : "Partner"}</th><th className="p-2 text-center">{isAr ? "مدين" : "Debit"}</th><th className="p-2 text-center">{isAr ? "دائن" : "Credit"}</th></tr></thead><tbody>{lines.map((line, i) => <tr key={i} className="border-t border-white/5"><td className="p-2 text-white font-semibold">{line.account}</td><td className="p-2 text-white/70">{line.partner}</td><td className="p-2 text-center font-mono text-emerald-300">{line.debit ? fmt(line.debit) : "—"}</td><td className="p-2 text-center font-mono text-rose-300">{line.credit ? fmt(line.credit) : "—"}</td></tr>)}</tbody></table><p className="text-[10px] text-white/55">{isAr ? "يمكن تعديل الحساب والشريك قبل اعتماد القيد." : "Account and partner are editable before approval."}</p></div>;
}

export default function JournalEntrySuggestionsEditor({ rows, isAr, bankAccountLabel }: { rows: Transaction[]; isAr: boolean; bankAccountLabel: string }) {
  const [accounts, setAccounts] = useState<LookupOption[]>([]);
  const [partners, setPartners] = useState<LookupOption[]>([]);
  useEffect(() => { let alive = true; async function load() { const companyId = localStorage.getItem("selectedCompanyId") || ""; const qs = companyId ? `?company_id=${companyId}` : ""; try { const [ar, pr] = await Promise.all([fetch(`${API_BASE_URL}/api/v1/erp/accounts${qs}`), fetch(`${API_BASE_URL}/api/v1/erp/partners${qs}`)]); const ad = ar.ok ? await ar.json() : []; const pd = pr.ok ? await pr.json() : []; if (!alive) return; setAccounts((Array.isArray(ad) ? ad : ad.accounts || []).map((a: any) => ({ id: a.id, code: a.code || "", name: a.name || "", label: `${a.code || ""} ${a.name || ""}`.trim() }))); setPartners((Array.isArray(pd) ? pd : pd.partners || []).map((p: any) => ({ id: p.id, name: p.name || p.display_name || "", label: `${p.name || p.display_name || ""}${p.vat ? ` - ${p.vat}` : ""}`.trim() }))); } catch (err) { console.warn("Failed to load entry lookups", err); } } load(); return () => { alive = false; }; }, []);
  const bank = bankAccountLabel || "الحساب البنكي المحدد في شاشة المطابقة";
  return <div className="space-y-3"><div className="rounded-xl border border-cyan-500/30 bg-cyan-500/10 p-3 text-[11px] text-white/70"><p className="font-bold text-cyan-300 mb-1">🧠 {isAr ? "اقتراح القيود بطريقة NLP / Semantic Matching" : "Journal suggestions using NLP / Semantic Matching"}</p><p>{isAr ? "الحساب والشريك قابلان للتعديل. الافتراضي يتم اختياره من دليل الحسابات والشركاء حسب المعنى المفهوم من وصف العملية في كشف البنك." : "Account and partner are editable. Defaults are selected from chart of accounts and partners using semantic meaning from bank statement description."}</p><p className="mt-2 text-cyan-300 font-bold">{isAr ? "الحساب البنكي المستخدم:" : "Bank account used:"} {bank}</p></div><div className="grid xl:grid-cols-2 gap-3">{rows.map((txn, idx) => <EntryRow key={idx} txn={txn} index={idx} isAr={isAr} bankAccount={bank} accounts={accounts} partners={partners} />)}</div></div>;
}
