"use client";

import { useEffect, useMemo, useState } from "react";
import { API_BASE_URL } from "@/lib/api";

interface Transaction { date: string; description: string; main_description?: string; details?: string[]; amount: number; debit?: number | null; credit?: number | null; ai_suggested_account?: string; }
interface LookupOption { id?: number | string; code?: string; name: string; label: string; }
interface EditableLine { account: string; description: string; partner: string; analytic: string; debit: number; credit: number; }

function fmt(value?: number | null) { return Number(value || 0).toLocaleString("en-SA", { minimumFractionDigits: 2, maximumFractionDigits: 2 }); }
function clean(value?: string) { return (value || "").toLowerCase().replace(/[أإآ]/g, "ا").replace(/ى/g, "ي").replace(/ة/g, "ه").replace(/[\-_/.,:;()\[\]{}]/g, " ").replace(/\s+/g, " ").trim(); }
function textOf(txn: Transaction) { return clean(`${txn.description} ${txn.main_description || ""} ${(txn.details || []).join(" ")} ${txn.ai_suggested_account || ""}`); }
function isDeposit(txn: Transaction) { return Number(txn.amount || 0) > 0 || (Number(txn.credit || 0) > 0 && Number(txn.debit || 0) === 0); }
function asOptions(data: any): LookupOption[] { const arr = Array.isArray(data) ? data : data?.accounts || data?.partners || data?.analytic_accounts || data?.analyticAccounts || []; return arr.map((x: any) => ({ id: x.id, code: x.code || "", name: x.name || x.display_name || "", label: `${x.code || ""} ${x.name || x.display_name || ""}${x.vat ? ` - ${x.vat}` : ""}`.trim() })).filter((x: LookupOption) => x.label); }
function extractAnalytics(kb: any): LookupOption[] { const raw = kb?.analytic_accounts || kb?.analyticAccounts || kb?.analytics || kb?.analytic || kb?.financial_structure?.analytic_accounts || kb?.data?.analytic_accounts || []; return asOptions(raw); }
function termsFor(text: string) { if (/رسوم|عموله|charge|fee|commission/.test(text)) return ["مصروفات بنكية", "رسوم", "bank", "fee"]; if (/راتب|رواتب|salary|payroll|wps/.test(text)) return ["رواتب", "اجور", "salary", "payroll"]; if (/مورد|vendor|supplier|فاتوره|bill|purchase|سداد|sadad/.test(text)) return ["مورد", "موردون", "payable", "supplier", "vendor"]; if (/عميل|customer|client|تحصيل|ايراد|receipt|deposit|ايداع/.test(text)) return ["عميل", "عملاء", "receivable", "revenue", "customer"]; if (/ضريبه|vat|tax|زكاه|زكاة/.test(text)) return ["ضريبة", "vat", "tax", "زكاة"]; if (/ايجار|rent|lease/.test(text)) return ["ايجار", "rent", "lease"]; return ["تسوية", "وسيط", "suspense", "clearing"]; }
function score(label: string, text: string, terms: string[]) { const l = clean(label); let s = 0; terms.forEach(t => { if (l.includes(clean(t))) s += 10; }); l.split(" ").filter(t => t.length > 2).forEach(t => { if (text.includes(t)) s += 2; }); text.split(" ").filter(t => t.length > 3).forEach(t => { if (l.includes(t)) s += 1; }); return s; }
function bestLabel(options: LookupOption[], text: string, terms: string[], minScore: number) { let best = { label: "", score: 0 }; options.forEach(o => { const sc = score(o.label, text, terms); if (sc > best.score) best = { label: o.label, score: sc }; }); return best.score >= minScore ? best.label : ""; }
function fallbackAccount(txn: Transaction) { const t = textOf(txn); if (txn.ai_suggested_account) return txn.ai_suggested_account; if (/رسوم|عموله|charge|fee|commission/.test(t)) return "مصروفات بنكية"; if (/راتب|رواتب|salary|payroll|wps/.test(t)) return "مصروفات الرواتب والأجور"; if (/مورد|vendor|supplier|فاتوره|bill|purchase|سداد|sadad/.test(t)) return "الموردون / مصروفات تحت التسوية"; if (/عميل|customer|client|تحصيل|ايراد|receipt|deposit|ايداع/.test(t)) return "العملاء / إيرادات تحت التسوية"; if (/ضريبه|vat|tax|زكاه|زكاة/.test(t)) return "ضرائب ورسوم حكومية"; if (/ايجار|rent|lease/.test(t)) return "مصروفات الإيجار"; return "حساب وسيط للمطابقة - يحتاج اعتماد"; }
function makeLines(txn: Transaction, bank: string, account: string, partner: string, analytic: string): EditableLine[] { const amount = Math.abs(Number(txn.amount || txn.credit || txn.debit || 0)); const desc = txn.main_description || txn.description || "عملية من كشف البنك"; const bankLine = { account: bank, description: desc, partner, analytic, debit: isDeposit(txn) ? amount : 0, credit: isDeposit(txn) ? 0 : amount }; const otherLine = { account, description: desc, partner, analytic, debit: isDeposit(txn) ? 0 : amount, credit: isDeposit(txn) ? amount : 0 }; return isDeposit(txn) ? [bankLine, otherLine] : [otherLine, bankLine]; }

function EntryRow({ txn, index, isAr, bankAccount, accounts, partners, analytics }: { txn: Transaction; index: number; isAr: boolean; bankAccount: string; accounts: LookupOption[]; partners: LookupOption[]; analytics: LookupOption[] }) {
  const t = textOf(txn);
  const oneAccount = useMemo(() => bestLabel(accounts, t, termsFor(t), 8) || fallbackAccount(txn), [accounts, t, txn]);
  const onePartner = useMemo(() => bestLabel(partners, t, [], 4) || "", [partners, t]);
  const oneAnalytic = useMemo(() => bestLabel(analytics, t, [], 4), [analytics, t]);
  const [edited, setEdited] = useState(false);
  const [lines, setLines] = useState<EditableLine[]>(() => makeLines(txn, bankAccount, oneAccount, onePartner, oneAnalytic));
  useEffect(() => { if (!edited) setLines(makeLines(txn, bankAccount, oneAccount, onePartner, oneAnalytic)); }, [txn, bankAccount, oneAccount, onePartner, oneAnalytic, edited]);
  const update = (row: number, key: keyof EditableLine, value: string) => { setEdited(true); setLines(prev => prev.map((line, i) => i === row ? { ...line, [key]: value } : line)); };
  const amount = Math.abs(Number(txn.amount || txn.credit || txn.debit || 0));
  return <div className="rounded-xl border border-cyan-500/25 bg-cyan-500/5 p-3 space-y-3"><div className="flex justify-between gap-3 flex-wrap"><div><p className="font-bold text-cyan-300">🧾 {isAr ? "قيد مقترح واحد" : "One suggested entry"} #{index + 1}</p><p className="text-[10px] text-white/60">{txn.date} — {txn.main_description || txn.description}</p></div><p className="font-mono text-amber-300 font-bold">{fmt(amount)} SAR</p></div><div className="overflow-auto rounded-lg border border-white/10"><table className="w-full min-w-[980px] text-[10px]"><thead className="bg-white/5 text-white/60"><tr><th className="p-2 text-right">{isAr ? "الحساب" : "Account"}</th><th className="p-2 text-right">{isAr ? "الوصف" : "Description"}</th><th className="p-2 text-right">{isAr ? "الشريك" : "Partner"}</th><th className="p-2 text-right">{isAr ? "الحساب التحليلي" : "Analytic account"}</th><th className="p-2 text-center">{isAr ? "مدين" : "Debit"}</th><th className="p-2 text-center">{isAr ? "دائن" : "Credit"}</th></tr></thead><tbody>{lines.map((line, i) => <tr key={i} className="border-t border-white/5"><td className="p-2"><input value={line.account} onChange={e => update(i, "account", e.target.value)} className="w-full bg-black/40 border border-white/10 rounded px-2 py-1 text-white outline-none" /></td><td className="p-2"><input value={line.description} onChange={e => update(i, "description", e.target.value)} className="w-full bg-black/40 border border-white/10 rounded px-2 py-1 text-white outline-none" /></td><td className="p-2"><input value={line.partner} onChange={e => update(i, "partner", e.target.value)} className="w-full bg-black/40 border border-white/10 rounded px-2 py-1 text-white outline-none" /></td><td className="p-2"><input value={line.analytic} onChange={e => update(i, "analytic", e.target.value)} className="w-full bg-black/40 border border-white/10 rounded px-2 py-1 text-white outline-none" /></td><td className="p-2 text-center font-mono text-emerald-300">{line.debit ? fmt(line.debit) : "—"}</td><td className="p-2 text-center font-mono text-rose-300">{line.credit ? fmt(line.credit) : "—"}</td></tr>)}</tbody></table></div><p className="text-[10px] text-white/55">{isAr ? "تم وضع اقتراح واحد فقط داخل القيد نفسه، ويمكن تعديل الحساب والوصف والشريك والحساب التحليلي في نفس موقعها." : "Only one default suggestion is inserted inside the entry itself. Account, description, partner, and analytic account are editable in place."}</p></div>;
}

export default function JournalEntrySuggestionsEditor({ rows, isAr, bankAccountLabel }: { rows: Transaction[]; isAr: boolean; bankAccountLabel: string }) {
  const [accounts, setAccounts] = useState<LookupOption[]>([]);
  const [partners, setPartners] = useState<LookupOption[]>([]);
  const [analytics, setAnalytics] = useState<LookupOption[]>([]);
  useEffect(() => { let alive = true; async function load() { const companyId = localStorage.getItem("selectedCompanyId") || ""; const qs = companyId ? `?company_id=${companyId}` : ""; try { const [ar, pr, dr] = await Promise.all([fetch(`${API_BASE_URL}/api/v1/erp/accounts${qs}`), fetch(`${API_BASE_URL}/api/v1/erp/partners${qs}`), fetch(`${API_BASE_URL}/api/v1/erp/discovery`)]); const ad = ar.ok ? await ar.json() : []; const pd = pr.ok ? await pr.json() : []; const dd = dr.ok ? await dr.json() : {}; if (!alive) return; setAccounts(asOptions(ad)); setPartners(asOptions(pd)); setAnalytics(extractAnalytics(dd)); } catch (err) { console.warn("Failed to load entry lookups", err); } } load(); return () => { alive = false; }; }, []);
  const bank = bankAccountLabel || "الحساب البنكي المحدد في شاشة المطابقة";
  return <div className="space-y-3"><div className="rounded-xl border border-cyan-500/30 bg-cyan-500/10 p-3 text-[11px] text-white/70"><p className="font-bold text-cyan-300 mb-1">🧠 {isAr ? "اقتراح قيد واحد قابل للتعديل" : "One editable suggested entry"}</p><p>{isAr ? "حساب البنك هو نفس الحساب المختار في المطابقة. لا تظهر عدة اقتراحات؛ يتم وضع اقتراح واحد داخل سطر القيد نفسه." : "Bank account is the same account selected in matching. No multiple suggestions are shown; one default suggestion is inserted directly in the entry line."}</p><p className="mt-2 text-cyan-300 font-bold">{isAr ? "حساب البنك:" : "Bank account:"} {bank}</p></div><div className="grid xl:grid-cols-1 gap-3">{rows.map((txn, idx) => <EntryRow key={idx} txn={txn} index={idx} isAr={isAr} bankAccount={bank} accounts={accounts} partners={partners} analytics={analytics} />)}</div></div>;
}
